services:
  dta:
    container_name: dta
    image: ghcr.io/aalto-speech/dta-server:staging
    restart: unless-stopped
    volumes:
      - dta-data:/data
      - hf-models:/hf/models
      - hf-cache:/hf/cache
    environment:
      APP_ENV: ${APP_ENV:-development}
      DATABASE: ${DATABASE:-dta.db}
      ADMIN_API_KEY: ${ADMIN_API_KEY:-}

  caddy:
    container_name: caddy
    image: docker.io/caddy:2.11-alpine
    restart: unless-stopped
    depends_on:
      - dta
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      # See Caddyfile for usage of these variables
      DOMAIN: ${DOMAIN:-localhost}
      ACME_EMAIL: ${ACME_EMAIL:-}
      UPSTREAM: ${UPSTREAM:-dta:8000} # [service|IP]:port
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-config:/config
      - caddy-data:/data
      - caddy-logs:/var/log/caddy

volumes:
  dta-data:
  caddy-config:
  caddy-data:
  caddy-logs:
    external: true
  hf-models:
    external: true
  hf-cache:
    external: true
