name: dta-server
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.14.3
  - pytorch
  - ffmpeg
  - transformers
  - torchaudio
  - openai-whisper
  - gunicorn
  - python-levenshtein
  - fastapi
  - python-dotenv
  - pydantic>=2,<3
