name: dta-server
channels:
  - defaults
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.14.3
  - ffmpeg=8.0
  - transformers=4.57
  - torchaudio=2.5
  - python-levenshtein=0.27
  - fastapi=0.128

