FROM mcr.microsoft.com/devcontainers/miniconda:1-3
# FROM docker.io/continuumio/miniconda3

COPY environment.yaml /tmp/conda-tmp/
RUN if [ -f "/tmp/conda-tmp/environment.yaml" ]; then umask 0002 && /opt/conda/bin/conda env update -n base -f /tmp/conda-tmp/environment.yaml; fi \
    && rm -rf /tmp/conda-tmp

RUN conda install -c conda-forge -y pylint pytest
