name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]

jobs:
  test-and-lint:
    name: Test and Lint on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: environment.yaml

      - name: Check conda and Python version
        shell: bash -l {0}
        run: |
          conda info
          python --version

      - name: Install test and linter dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge pytest pylint

      - name: Lint with pylint
        shell: bash -l {0}
        run: |
          pylint app/

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest tests/
